
name: Linux CI

on:
  push:
    branches:
      - master

jobs:
  build_release:
    strategy:
      matrix:
        os: [ubuntu-22.04]   #ubuntu-latest
        #qt6: ["ON", "OFF"]
        compiler:
          - { cc: gcc-11, cxx: g++-11 }
          - { cc: gcc-13, cxx: g++-13 }
          - { cc: gcc-17, cxx: g++-17 }
          - { cc: gcc, cxx: g++ }  # Latest version
          - { cc: clang-11, cxx: clang++-11 }
          - { cc: clang-15, cxx: clang++-15 }
      fail-fast: false

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }};${{ matrix.compiler.cxx }}   #; #qt5-${{ matrix.qt6 }}
    
    timeout-minutes: 20

    steps:
    
    - name: Install configure system
      run: |
        sudo apt update
        sudo apt install ${{ matrix.compiler.cc }} ninja-build cmake gdal-bin libgdal-de libboost-dev libboost-date-time-dev libboost-test-dev
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure
      run: cmake --preset=gprof_pg_flag -DCMAKE_INSTALL_PREFIX=install_gprof

    - name: Build
      run: cmake --build --preset=gprof_pg_flag --target install

    - name: Run Tests
      run: ctest --preset test_gprof_pg_flag
